Lina-refactor
Lim-Ji-Hyeon/ReactShop pull request #11
Opened 2022-06-06 05:37 UTC by Lim-Ji-Hyeon

## 제목
공통 컴포넌트 코드 수정

## 작업 내용
- button.jsx, badge.jsx, theme.js, BreadCrumbs.jsx, Header.jsx 파일 수정

## 변경 로직 + 변경 이유
- 코드 리뷰 후 코드 수정
- theme 파일과 props 로직 수정

## 변경 전(관련 스크린샷 포함)
- theme 파일에 공통 컴포넌트 이름의 객체가 있었음

## 변경 후 (관련 스크린샷 포함)
- 공통 부분 빼고 나머지 객체 삭제
- theme 파일 스크린샷 
- 
![image](https://user-images.githubusercontent.com/74555791/172101086-3f002382-7ae0-4a25-a979-538e0ffb064b.png)
![image](https://user-images.githubusercontent.com/74555791/172101115-540a5a7d-5814-4c61-8f6a-be3c2b690c55.png)

2022-06-06 09:27 UTC, alice-l2 requested changes

2022-06-06 09:27 UTC, alice-l2 commented on src/App.jsx
> +        <StarRating rate={"4.3"}/>
테스트한 컴포넌트는 삭제하고 PR해주세요.

2022-06-06 09:27 UTC, alice-l2 commented on src/components/Footer.jsx
> +  const snsBrand = sns.map((item) => (<StyledSns key={item.id} href={item.url} target="_blank"><StyledImg key ={item.id} icon={item.image} title={item.name}/></StyledSns>))
key는 굳이 중복해서 넣지 않아도 될 것 같습니다.

2022-06-06 09:27 UTC, alice-l2 commented on src/components/common/Badge.jsx
> +const SBadge = styled.span`
SBadge 말고 더 적절한 이름으로 바꾸는 건 어떤가요?

2022-06-06 09:27 UTC, alice-l2 commented on src/components/common/Button.jsx
> +    <SButton type={type} color={color} borderRadius={borderRadius}>{children}</SButton>
SButton 말고 더 적절한 이름으로 바꾸는 건 어떤가요?

2022-06-06 09:27 UTC, alice-l2 commented on src/views/Fashion.jsx
> +
ThemeProvider가 중복 사용되고 있네요.

2022-06-07 05:04 UTC, alice-l2 commented on src/components/BreadCrumbs.jsx
> +const StyledDiv = styled.span`
StyledDiv 말고 더 의미 있는 이름으로 바꿔보는 거 어떨까요? span 태그로 만들었는데 왜 div인가요?

2022-06-07 05:16 UTC, alice-l2 commented on src/components/Button.jsx
> +
이 부분 삭제해도 좋을 것 같습니다.

2022-06-07 05:16 UTC, alice-l2 commented on src/components/Button.jsx
> +  }
` width : ${({theme, type}) => sizeFunction(type, theme)};` => ` width : ${({theme, type}) => theme.width[type])};`
이렇게 작성하면 위 function들을 삭제해도 될 것 같네요.

2022-06-07 08:28 UTC, Lim-Ji-Hyeon commented on src/components/Button.jsx
> +  }
네~!! 그렇네요^^

2022-06-07 09:06 UTC, alice-l2 approved these changes

2022-06-07 11:27 UTC, merged

2022-06-13 04:09 UTC, oinochoe commented on src/components/BreadCrumbs.jsx
> +const StyledDiv = styled.span`
StyledBreadCrumb와 같이 이름 짓기 어려우면 컴포넌트 명칭으로 따라가는 것을 우선시 하면 좋을 것 같습니다 : )
@Lim-Ji-Hyeon @alice-l2

2022-06-13 05:40 UTC, Lim-Ji-Hyeon commented on src/components/BreadCrumbs.jsx
> +const StyledDiv = styled.span`
> StyledBreadCrumb와 같이 이름 짓기 어려우면 컴포넌트 명칭으로 따라가는 것을 우선시 하면 좋을 것 같습니다 : ) @Lim-Ji-Hyeon @alice-l2

네~!! 참고하겠습니다^^